# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    ports:
      - 5000:5000

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: src/Services/basket/Basket.API/Dockerfile
    ports:
      - 5001:5001

volumes:
  mongo_data:
  portainer_data:
